databases:
  mysql:
    host: mysql
    username: admin
    password: abcd1234
    database: mvc
    port: 3306
  redis:
    host: redis
    port: 6379
    password:

logger:
  fluentd:
    host: fluentd
    port: 24224